# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Andrés Montenegro
tagline:          Building The Future One Day At A Time
description:      ""
url:              https://andresmontenegro.club
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Andrés Montenegro
  url:            https://twitter.com/AndresMSoftware

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/AndresMontenegroClub/AndresMontenegroClub.github.io
